version: "3"

services:
    app:
        build:
            context: ./.docker/app
            dockerfile: Dockerfile
        links:
            - db
        ports:
            - "80:80"
            - "443:433"
        volumes:
            - ./src:/var/www/html
    db:
        image: mysql:8.0.26
        restart: always
        environment:
            MYSQL_DATABASE: "db"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "secret"
            MYSQL_ROOT_PASSWORD: "secret"
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql
volumes:
    db-data:
